#
# Site settings
#
remote_theme: LeakyAbstractions/pretty-docs
url: https://www.google.com
baseurl: /pretty-docs
title: &site_title Integration Documentation
description: &site_description Integration Documentation
branding:
  icon:
    name: icon_documents_alt
  highlight: Payments
  bold: Integration Documentation
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: GolfNow
  copyright:
    notice: 2020 GolfNow


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
